substitutions:
  friendly_name: LightStripPro
  name: wyzelightstrippro

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: tdegenko.esphome-wyzelightstrippro
    version: "1.0"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

dashboard_import:
  package_import_url: github://tdegenko/esphome-customizations/wyze/lightstrip-pro-5m.yaml
  import_full_config: false # or true

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fallback Hotspot"
    password: "aiOc8OoF0Cyq"

captive_portal:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO2
      mode:
        input: true
        pullup: true
    name: "${friendly_name} side button"
    on_press:
      then:
          - voice_assistant.start:
    on_release:
      then:
          - voice_assistant.stop:
  - platform: gpio
    pin:
      number: GPIO19
      mode:
        input: true
        pullup: true
    name: "${friendly_name} top button"
    on_press:
      then:
        - light.toggle:
            id: light1
light:
  - platform: esp32_rmt_led_strip
    chipset: WS2812
    pin: GPIO25
    num_leds: 50
    rgb_order: BRG
    rmt_channel: 0
    id: light1
    name: "${friendly_name} light1"
    effects:
      - random:
      - pulse:
      - strobe:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:
  # For 10M Pro
  #- platform: esp32_rmt_led_strip
  #  chipset: WS2812
  #  pin: GPIO26
  #  num_leds: 50
  #  rgb_order: BRG
  #  rmt_channel: 1
  #  name: "${friendly_name} light2"
  #  effects:
  #    - random:
  #    - pulse:
  #    - strobe:
  #    - flicker:
  #    - addressable_rainbow:
  #    - addressable_color_wipe:
  #    - addressable_scan:
  #    - addressable_twinkle:
  #    - addressable_random_twinkle:
  #    - addressable_fireworks:
  #    - addressable_flicker:

#May work? could theoretically be used to configure the E7243
i2c:
  sda: GPIO18
  scl: GPIO23
  scan: true
  
i2s_audio:
  i2s_lrclk_pin: GPIO33
  i2s_bclk_pin: GPIO32
  i2s_mclk_pin: GPIO00

microphone:
  - platform: i2s_audio
    id: internal_mic
    pdm: false
    bits_per_sample: 32bit
    adc_type: external
    i2s_din_pin: GPIO36
    channel: right

voice_assistant:
  microphone: internal_mic
  on_start:
    - light.turn_on:
        id: light1
        blue: 100%
        red: 0%
        green: 0%
        effect: none
  on_tts_start:
    - light.turn_on:
        id: light1
        blue: 0%
        red: 0%
        green: 100%
        effect: none
  on_tts_end:
    - light.turn_on:
        id: light1
        blue: 0%
        red: 0%
        green: 100%
        effect: pulse
  on_end:
    - delay: 1s
    - light.turn_off: light1
  on_error:
    - light.turn_on:
        id: light1
        blue: 0%
        red: 100%
        green: 0%
        effect: none
    - delay: 1s
    - light.turn_off: light1

switch:
  - platform: restart
    name: ${friendly_name} Restart
