substitutions:
  friendly_name: "Sonoff S31"
  name: "sonoff-s31"
  restore_mode: ALWAYS_OFF

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: tdegenko.esphome-sonoff-s31 
    version: "1.02"

esp8266:
  board: esp12e

dashboard_import:
  package_import_url: github://tdegenko/esphome-customizations/sonoff/s31.yaml
  import_full_config: false # or true

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fallback Hotspot"
    password: "aiOc8OoF0Cyq"

captive_portal:

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)
  
# Remove this line if you're not using Home Assistsant or your switch will restart every now and again
api:

ota:
  platform: esphome

# Device Specific Config

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Status"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  - platform: cse7766
    current:
      name: "Current"
      accuracy_decimals: 1
      filters:
        - throttle_average: 60s
    voltage:
      name: "Voltage"
      accuracy_decimals: 1
      filters:
        - throttle_average: 60s
    power:
      name: "Power"
      accuracy_decimals: 1
      id: my_power
      filters:
        - throttle_average: 60s
    energy:
      name: "Energy"
      accuracy_decimals: 2
      filters:
        - throttle: 60s
    apparent_power: #(only available with version 2024.3.0 or greater)
      name: "Apparent Power"
      filters:
        - throttle_average: 60s
    power_factor: #(only available with version 2024.3.0 or greater)
      name: "Power Factor"
      accuracy_decimals: 2
      filters:
        - throttle_average: 60s
  - platform: total_daily_energy
    name: "Daily Energy"
    power_id: my_power

switch:
  - platform: gpio
    name: "None"
    pin: GPIO12
    id: relay
    restore_mode: "${restore_mode}"
  - platform: restart
    name: "Restart"


time:
  - platform: homeassistant
    id: homeassistant_time

status_led:
  pin:
    number: GPIO13
    inverted: True
