---
substitutions:
  friendly_name: "Treatlife SL20"
  name: "treatlife-sl20"
  restore_mode: ALWAYS_ON
  light_transition_length: 1s
  pwm_freq: 1000Hz

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: tdegenko.esphome-treatlife-sl20
    version: "1.03"

bk72xx:
  board: generic-bk7231t-qfn32-tuya

dashboard_import:
  package_import_url: github://tdegenko/esphome-customizations/treatlife/sl20.yaml
  import_full_config: false     # or true

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fallback Hotspot"
    password: "aiOc8OoF0Cyq"

captive_portal:

logger:

api:

ota:
  platform: esphome

output:
  - platform: libretiny_pwm
    pin: PWM2
    inverted: false
    id: cw_pwm
    frequency: "${pwm_freq}"

  - platform: libretiny_pwm
    pin: PWM3
    inverted: false
    id: ww_pwm
    frequency: "${pwm_freq}"
light:
  - platform: cwww
    name: None
    id: cwww_led
    cold_white: cw_pwm
    warm_white: ww_pwm
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2500 K
    constant_brightness: true
    restore_mode: "${restore_mode}"
    default_transition_length: "${light_transition_length}"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

switch:
  - platform: restart
    name: "Restart"
